# Database
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/ngo_events
spring.datasource.username=springuser
spring.datasource.password=040600
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=9c618d4701a3c4
spring.mail.password=af7a13d758134b
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App
spring.application.name=ngo-events
server.port=8080
